-- SELECT count(category) AS "Category" FROM category; 
-- Réponse : 16;
---------------------------------------------------------------
-- SELECT sum(amount) AS "Somme des locations" FROM payment;
-- Réponse : 61312.04;
---------------------------------------------------------------
-- SELECT count(film) AS "Film" FROM film WHERE title LIKE 'J%';
-- Réponse : 20;
-----------------------------------------------------------------
-- SELECT count(first_name) AS "Prénom" FROM actor WHERE first_name ILIKE 'a%' OR first_name ILIKE 'e%' OR first_name ILIKE 'i%' OR first_name ILIKE 'o%' OR first_name ILIKE 'u%' OR first_name ILIKE 'y%';
-- Réponse : 24;
-- OR SELECT count(first_name) AS "Prénom" FROM actor WHERE first_name SIMILAR TO '(A|E|I|O|U|Y)%';
----------------------------------------------------------------------
-- SELECT CONCAT(first_name, ' ',last_name) AS "Résultat" FROM customer WHERE first_name ILIKE 'E%' AND address_id < 500 ORDER BY customer_id DESC LIMIT 1;
-- Eddie
----------------------------------------------------------------------
-- SELECT  customer_id, sum(amount)
-- FROM payment
-- WHERE staff_id = 2
-- GROUP BY 1
-- HAVING sum(amount) >= 110;

--------------------------------------------------------------------------------
